CREATE TABLE SECTION (
  IdSection     INTEGER,
  NomSection    VARCHAR(100),
  PRIMARY KEY (IdSection ASC)
);
INSERT INTO SECTION(NomSection)VALUES('DEFAUT');

ALTER TABLE PERSONNE ADD IdSection INTEGER REFERENCES SECTION(IdSection);
UPDATE PERSONNE SET IdSection = 1;

ALTER TABLE Formalite ADD IdSection INTEGER REFERENCES SECTION(IdSection);
UPDATE Formalite SET IdSection = 1;